name: Daily Football + DBT Pipeline

on:
  schedule:
    # Every day at 1:35 AM Amsterdam time (CET/CEST)
    - cron: '35 0 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests python-dotenv google-cloud-bigquery pyarrow

    - name: Install dbt for BigQuery
      run: pip install dbt-bigquery

    - name: Write GCP service account key
      run: echo "${{ secrets.GCP_BASE }}" > $HOME/gcp_key.json

    - name: Run Python pipeline
      run: python pipeline.py
      env:
        FOOTBALL_API_TOKEN: ${{ secrets.FOOTBALL_API_TOKEN }}
        GCP_BASE_PATH: $HOME/gcp_key.json

    - name: Run dbt models
      working-directory: ./dbt
      run: dbt run --profiles-dir ./dbt
      env:
        GCP_BASE_PATH: $HOME/gcp_key.json